yrke_list =["Lärare",
"Läkare",
"Utvecklare",
"Sjuksköterska",
"Kock",
"Operatör",
"Personlig assistent",
"Mekaniker",
"Butikssäljare",
"Civilingenjör",
"Projektledare",
"Städare"]

lan_list = [(2, "Västra Götalands län"),
(3,  "Västmanlands län"),
(4,  "Västernorrlands län"),
(5,  "Västerbottens län"),
(6,  "Värmlands län"),
(7,  "Uppsala län"),
(8,  "Södermanlands län"),
(9,  "Stockholms län"),
(10, "Skåne län"),
(11, "Örebro län"),
(12, "Norrbottens län"),
(13, "Kalmar län"),
(14, "Jönköpings län"),
(15, "Jämtlands län"),
(16, "Hallands län"),
(17, "Gävleborgs län"),
(18, "Gotlands län"),
(19, "Dalarnas län"),
(20, "Blekinge län")]

# Östergötlands län
# Kronobergs län