# List of counties
counties = [
    (2,  "västra Götalands län"),
    (3,  "västmanlands län"),
    (4,  "västernorrlands län"),
    (5,  "västerbottens län"),
    (6,  "värmlands län"),
    (7,  "uppsala län"),
    (8,  "södermanlands län"),
    (9,  "stockholms län"),
    (10, "skåne län"),
    (11, "örebro län"),
    (12, "norrbottens län"),
    (13, "kalmar län"),
    (14, "jönköpings län"),
    (15, "jämtlands län"),
    (16, "hallands län"),
    (17, "gävleborgs län"),
    (18, "gotlands län"),
    (19, "dalarnas län"),
    (20, "blekinge län"),
    (22, "kronobergs län"),
    (23, "östergötlands län")]